Fix message length problem
Mrs4s/MiraiGo pull request #138
Opened 2021-03-20 10:21 UTC by sam01101

逻辑判断错误

2021-03-20 13:24 UTC, Mrs4s requested changes

2021-03-20 13:24 UTC, Mrs4s commented on client/private_msg.go
> -	if msgLen > 5000 || imgCount > 50 {
这地方应该把上面 `EstimateLength` 的 `limit` 改为 `5000`

2021-03-20 13:25 UTC, sam01101 commented on client/private_msg.go
> -	if msgLen > 5000 || imgCount > 50 {
草, 为什么没改到
我记得我改了的

2021-03-20 13:36 UTC, sam01101 commented
ok

2021-03-23 11:15 UTC, Mrs4s approved these changes

2021-03-23 11:15 UTC, merged