添加群打卡接口 （看起来是这个包
Mrs4s/MiraiGo pull request #273
Opened 2022-05-14 14:10 UTC by synodriver

2022-05-14 14:28 UTC, wdvxdr1123 commented
We use `protoc-gen-golite` instead of `protoc-gen-go`, you can install it by running:
```bash
go install github.com/RomiChan/protobuf/cmd/protoc-gen-golite@latest
```

2022-05-14 14:33 UTC, synodriver commented
如果有问题请昵昵指教QAQ

> ```shell
> github.com/RomiChan/protobuf/cmd/protoc-gen-golite
> ```

那个东西怎么用的（

2022-05-14 15:03 UTC, synodriver commented
我修了

2022-05-15 13:04 UTC, Mrs4s requested changes

2022-05-15 13:04 UTC, Mrs4s commented on client/daka.go
> +	body := &oidb.Oidb_0Xeb7_ReqBody{
oidb实体请参考已有包的命名规则

2022-05-17 05:26 UTC, synodriver commented on client/daka.go
> +	body := &oidb.Oidb_0Xeb7_ReqBody{
可是pb出来就是这种QAQ

2022-05-17 05:26 UTC, synodriver commented on client/daka.go
> +	body := &oidb.Oidb_0Xeb7_ReqBody{
我再看看

2022-05-17 11:30 UTC, synodriver commented
done

2022-05-24 05:31 UTC, merged