fix: 修复空指针可能导致panic的问题
Mrs4s/MiraiGo pull request #293
Opened 2022-08-11 13:06 UTC by asjdf

> panic: interface conversion: interface {} is nil, not *client.GroupSystemMessages
> 
> goroutine 31 [running]:
> github.com/Mrs4s/MiraiGo/client.(*QQClient).GetGroupSystemMessages(0x19919ab95fdf8?)
>         C:/Users/atom/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220720124026-5c0e2c5773de/client/system_msg.go:51 +0x305

2022-08-11 13:12 UTC, qianjunakasumi commented
最佳的修复方法应该是：检查 `sendAndWait` 函数在非 err 情况下仍会返回 nil 的位置，并在此修正

2022-08-11 13:13 UTC, asjdf commented
> 最佳的修复方法应该是：检查 `sendAndWait` 函数在非 err 情况下仍会返回 nil 的位置，并在此修正

检查中，暂时没想明白

2022-08-11 13:14 UTC, asjdf commented
感谢迅速的回复

2022-08-16 16:19 UTC, qianjunakasumi commented
彻底解决此问题可能需要动态复现并追踪。

建议临时解决方案是直接在 Line 183 处判断 `res.Response` 是否为 `nil`，自定义 error 消息并返回，以避免 panic

2022-08-16 17:11 UTC, asjdf commented
目前复现有一定的难度，我暂时还未能稳定复现此问题。

2022-08-16 17:17 UTC, qianjunakasumi requested changes
不能简单在 `res.Response` 空时直接返回自定义 err，必须同时满足 `rsp.Error` 也为空

2022-08-16 17:21 UTC, Mrs4s commented
这个地方应该检查相应 `decode` 函数的逻辑, 而不是直接在上游函数加个简单判断

2022-08-16 17:22 UTC, asjdf commented
啊啊 非常抱歉

2022-08-16 17:24 UTC, asjdf commented
请问大佬们有交流群之类的吗？

2022-12-27 05:49 UTC, closed without merging