修复 因为媒体服务器不存在 而导致的 panic - 数组溢出 ,并且新增媒体服务器提示状态.
Mrs4s/MiraiGo pull request #347
Opened 2024-02-24 18:29 UTC by SudoSuBash

修复 因为媒体服务器不存在 而导致的 panic - 数组溢出 ,并且新增媒体服务器提示状态
对应Issue:
Mrs4s/go-cqhttp#2517
Mrs4s/go-cqhttp#2521

现在可以和  Mrs4s/go-cqhttp#2522 一起配合检测媒体服务器是否存在.

2024-02-26 12:46 UTC, fumiama requested changes

2024-02-26 12:46 UTC, fumiama commented on client/internal/highway/highway.go
> +		Addre := [4]int{1936450177, 3211518593, 761732366, 993564539}
用人类可读的形式。如`net.IPv4(1, 2, 3, 4)`或`netip.AddrFrom4()`等。另外，考虑把它放到全局变量以方便修改/新增。

2024-02-26 12:46 UTC, fumiama commented on client/internal/highway/highway.go
> +		Addre := [4]int{1936450177, 3211518593, 761732366, 993564539}
所有变量名首字母小写。

2024-02-26 12:46 UTC, fumiama commented on client/internal/highway/highway.go
> +		//fmt.Println("test")
删除不用的注释。

2024-02-26 14:57 UTC, SudoSuBash commented on client/internal/highway/highway.go
> +		Addre := [4]int{1936450177, 3211518593, 761732366, 993564539}
抱歉，请把我这个pull requests关了吧，不用merge，目前测试，这种方法在发送语音时仍会报错199。
目前不知道有好的解决方案

2024-02-26 15:17 UTC, fumiama commented
你不用关掉再开PR，直接继续更改就可以了。

2024-02-29 16:07 UTC, fumiama commented on client/internal/highway/highway.go
> +		Addre := [4]int{1936450177, 3211518593, 761732366, 993564539}
ok.

2024-02-29 16:07 UTC, fumiama commented on client/internal/highway/highway.go
> +		Addre := [4]int{1936450177, 3211518593, 761732366, 993564539}
pr是删不掉的，只能close。

2024-02-29 16:07 UTC, closed without merging

2024-03-20 09:28 UTC, SinKingCloud commented
经过测试可以调用UploadImage方法来让服务端主动返回server list。但是上传群文件只能上传txt类型的。估计协议已经更新了。需要抓包才能彻底修复。
<img width="1104" alt="image" src="https://github.com/Mrs4s/MiraiGo/assets/56614045/735f7dfa-bd10-47d1-8be1-d2ed4d544ca0">

2024-10-22 10:34 UTC, kkgg0521 commented
> 经过测试可以调用UploadImage方法来让服务端主动返回server list。但是上传群文件只能上传txt类型的。估计协议已经更新了。需要抓包才能彻底修复。 <img alt="image" width="1104" src="https://private-user-images.githubusercontent.com/56614045/314442956-735f7dfa-bd10-47d1-8be1-d2ed4d544ca0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1OTM1MjUsIm5iZiI6MTcyOTU5MzIyNSwicGF0aCI6Ii81NjYxNDA0NS8zMTQ0NDI5NTYtNzM1ZjdkZmEtYmQxMC00N2QxLThiZTEtZDJlZDRkNTQ0Y2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDEwMzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxM2UxOWIzMjFiZDZhZmNkMTM4ZDZiZGJiZDM5MDc1MTM4ZjU3ZjIwYmM5MWYwNzY4YWU4Yzc1Mjg5NGFiZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aoa8sgoDprALSVTbBnBg5NKrdMDMUD5xbbbJVcvRUr4">

看了一下應該是丟包導致的