fix: panic occurred when receive voice record in group message
Mrs4s/MiraiGo pull request #349
Opened 2024-09-03 07:13 UTC by Fripine

Protocol: Android Pad 9.0.90.18945

2024-09-04 09:53 UTC, fumiama requested changes

2024-09-04 09:53 UTC, fumiama commented on message/message.go
> +				if bt == 20 || bt == 10 {
用反向的条件判断，避免缩进。

2024-09-04 13:31 UTC, Fripine commented
吐槽一下这个PbMultiMediaElement感觉就不是自动生成的，像是手打上去的，我用protoc-gen-golite生成的格式完全不一样，以为搞坏了

2024-09-04 14:22 UTC, fumiama commented
> 吐槽一下这个PbMultiMediaElement感觉就不是自动生成的，像是手打上去的，我用protoc-gen-golite生成的格式完全不一样，以为搞坏了

用的是修改过的`github.com/RomiChan/protobuf/cmd/protoc-gen-golite`。详见根目录`Makefile`。

2024-09-05 01:32 UTC, Fripine commented
> > 吐槽一下这个PbMultiMediaElement感觉就不是自动生成的，像是手打上去的，我用protoc-gen-golite生成的格式完全不一样，以为搞坏了
> 
> 用的是修改过的`github.com/RomiChan/protobuf/cmd/protoc-gen-golite`。详见根目录`Makefile`。

我就是按照makefile里面的做的，安装了里面的特定版本，并且按照里面写的生成指令生成的，和原有的pb.go不一样

2024-09-05 02:19 UTC, wdvxdr1123 commented
应该是 https://github.com/Mrs4s/MiraiGo/pull/343 这里没有使用工具生成代码

2024-09-18 16:26 UTC, closed without merging